import type { Metadata } from "next";
import DashboardSidebar from "@/components/dashboardComponent/DashboardSidebar";
import DashboardHeader from "@/components/dashboardComponent/DashboardHeader"; // Correct


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=''
      >
         <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
          <DashboardHeader/>
          <div className="flex">
            <DashboardSidebar />
            <main className="flex-1 p-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}